version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Standard RabbitMQ port
      - "15672:15672"  # Management plugin
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017" 
    command: ["--quiet"]
    environment:
      MONGO_DB_HOST: host.docker.internal
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_DB_PORT: 27018
    volumes:
      - ./mongo_data:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s


  numbergenerator:
    build: ./numberGenerator  # Path to your number generator service directory
    ports:
      - "3001:3001"
    depends_on:
     - rabbitmq
    environment:
      NUMBER_GENERATOR_QUEUE: NUMBER_GENERATOR_QUEUE
      METADATA_CLIENT_QUEUE: METADATA_CLIENT_QUEUE
      DATABASE_CLIENT_QUEUE: DATABASE_CLIENT_QUEUE
      RABBITMQ_URL: amqp://guest:guest@rabbitmq  # Default credentials, adjusted URL
    networks:
      - app-network

  metadataclient:
    build: ./metadataClient  # Path to your number generator service directory
    ports:
      - "4001:4001"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq  # Default credentials, adjusted URL
    networks:
      - app-network

  databaseclient:
    build: ./databaseClient  # Path to your number generator service directory
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq  # Default credentials, adjusted URL
      MONGO_DB_URI: mongodb://mongo_user:mongo_pass@host.docker.internal:27018
      MONGO_DB_NAME: "phoneNumbers"


    networks:
      - app-network
  api:
    build: ./api  # Path to your number generator service directory
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    environment:
      MONGO_DB_URI: mongodb://mongo_user:mongo_pass@host.docker.internal:27018
      RABBITMQ_URL: amqp://guest:guest@rabbitmq  # Default credentials, adjusted URL
      MONGO_DB_NAME: phoneNumbers
      API_HOST: localhost
      PORT: 3000
    networks:
      - app-network



volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  app-network:
    driver: bridge
