version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5673:5672"  # Remapped AMQP protocol port
      - "15673:15672"  # Remapped Management UI port
    environment:
      RABBITMQ_ERLANG_COOKIE: 'TEST_SECRET_COOKIE'
      RABBITMQ_DEFAULT_USER: 'metadata_client_user'
      RABBITMQ_DEFAULT_PASS: 'metadata_client_password'
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q check_local_alarms
      interval: 1s
      timeout: 10s
      retries: 5
